config/routes.rb
Rails.application.routes.draw do
  root :to => 'patients#index'
  resources :patients do 
      collection do 
         get 'index'
         post 'add_patient'
         post 'edit_patient'
         post 'up_patient'
         get 'delete'
     end
     end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :name, :first_name, :archived
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  
  def up_patient
  #@patient = Patient.all
    unless params[:archive].nil?
        
       logger.info("########################table for id is ======== #{params[:archive].keys}")
    for index in params[:archive].keys do 
       logger.info("########################patient is ======== #{@patient.to_json}")
       logger.info("########################!!!!!! INDEX IS  ======== #{index.to_i} and !!! #{params[:archive].keys[index.to_i - 1].to_i }")
      #@patient.select{|b| b.id == params[:archived].keys[index.to_i-1]}.map{|p| p.archived}[0]= true
      #@patient = Patient.where(:id => params[:archive].keys[index.to_i - 1].to_i).first
      @patient = Patient.where(:id => index.to_i ).first
     @patient.archived = true
       @patient.save!
    end
       # @patient.save!
  end
    #@patients = Patient.all
    #respond_to do |format|
     # format.html
      #format.js
    #end
    redirect_to :action => 'index'
  end
  
  
  def add_patient
    
     @patient = Patient.new(patient_params)
     @patient.save
    #respond_to do |format|
     # if @patient.save
      #  format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
       # format.json { render :show, status: :created, location: @patient }
      #else
       # format.html { render :new }
        #format.json { render json: @patient.errors, status: :unprocessable_entity }
      #end
    #end
    redirect_to :action => 'index', notice: 'Patient was successfully created.'
  end
  
  def delete
     #@patient = Patient.find(:id => params[:id].to_i)
    Patient.destroy_all(:id => params[:p].to_i)
    redirect_to :action => 'index', notice: 'Patient was successfully deleted.'
  end
  
  def edit_patient
    @patient = Patient.where(:id => params[:patient][:id]).first
    @patient.name = params[:patient][:name]
    @patient.first_name = params[:patient][:first_name]
    @patient.archived= params[:patient][:archived]
    @patient.save
    #respond_to do |format|
      
       #if @patient.save!
        #format.html { redirect_to @patient, notice: 'Patient was successfully update.' }
        #format.json { render :show, status: :created, location: @patient }
      #else
       # format.html { render :new }
        #format.json { render json: @patient.errors, status: :unprocessable_entity }
      #end
      # end
      redirect_to :action => 'index', notice: 'Patient was successfully update.'
  end
 

  
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
     @patient = Patient.find(params[:id])
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :first_name, :archived)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient.rb
class Patient < ActiveRecord::Base
  
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "basic", :media => "all" %>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
			$(document).ready(function() {
			//	$('select').ieExpandSelectWidth();
			});
		</script>
</head>
<body>

<div class="container">
    <%= yield %>
</div>


</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :archived %><br>
    <%= f.check_box :archived %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/_modal_add_patient.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel">Ajouter un Patient</h4>
		      

                </div>
                
		 
		 
<%= form_for 'patient', :url => '/patients/add_patient', :id => "add_patientss", :html => { :class => "form-horizontal form_patient", :id => "add_patient_form"} do |g| %>

	
	
  <div class="modal-body">
  
  <div class="row-fluid modal_mat">
    <div class="span12">
    
       
    <div class="control-group">
      <label class="control-label"> Nom</label>     
        <div class="controls">
          <div class="input-append">
            <%= g.text_field :name, :class => 'span5', :required => true, :id => 'name_patient' %>
          </div>
        </div>
    </div>
    
    <div class="control-group">
      <label class="control-label">Prénom</label>     
        <div class="controls">
          <div class="input-append">
            <%= g.text_field :first_name, :class => 'span5', :required => true, :id => 'first_name_patient' %>
          </div>
        </div>
    </div>
     <div class="controls">
      <div class="input-append">
        
         <%= g.check_box :archived, :class => 'span5', :id => 'check'%>           
         
            <label class="control-label">Archivé</label> 
          </div>
        </div>
    
    </div>
    </div>
     <div class="actions">
    <%= g.submit 'Save', class: 'btn btn-primary' %>
  </div>
  
        
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <!--<button type="button" class="btn btn-primary">Save</button>-->
                </div>
             </div>
	       <%end%>
            </div>
        </div>
    </div>
</div>

app/views/patients/_modal_edit_patient.html.erb
<div class="modal fade" id="myModal_edit_<%= ing.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel"> Editer un Patient</h4>
		      

                </div>              
		 
		 
<%= form_for 'patient', :url => '/patients/edit_patient', :id => "edit_patientss", :html => { :class => "form-horizontal form_patient", :id => "add_patient_form"} do |g| %>

	
	
  <div class="modal-body">
  
  <div class="row-fluid modal_mat">
    <div class="span12"> 
       
    <div class="control-group">
      <label class="control-label"> Nom</label>     
        <div class="controls">
          <div class="input-append">
            <%= g.text_field :name, :class => 'span5', :required => true, :id => 'name_patient', :value => ing.name %>
          </div>
        </div>
    </div>
    
    <div class="control-group">
      <label class="control-label">Prénom</label>     
        <div class="controls">
          <div class="input-append">
            <%= g.text_field :first_name, :class => 'span5', :required => true, :id => 'first_name_patient', :value => ing.first_name %>
          </div>
        </div>
    </div>
     
     <div class="controls">
      <div class="input-append">
        <%if ing.archived == true %>
         <%= g.check_box :archived, :class => 'span5', :id => 'check', :checked => true%>           
         <%else%>
           <%= g.check_box :archived, :class => 'span5', :id => 'check', :checked => false %>           
         <%end%>
            <label class="control-label">Archivé</label> 
          </div>
        </div>
    
     <%= g.hidden_field :id, :value => ing.id %>
    </div>
    </div>
  
     <div class="actions">
    <%= g.submit 'Editer', class: 'btn btn-primary' %>
  </div>
  
        
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <!--<button type="button" class="btn btn-primary">Save</button>-->
                </div>
             </div>
	       <%end%>
            </div>
        </div>
    </div>
</div>

app/views/patients/_modal_up_patient.html.erb
<div class="modal fade" id="myModal_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span>

                    </button>
                     <h4 class="modal-title" id="myModalLabel"> Les fiches des patients</h4>
		      

                </div>              
		 
		 
<%#= form_for 'fiche', :url => '/patients/up_patient', :id => "up_patientss", :html => { :class => "form-horizontal form_patient", :id => "add_patient_form", :remote => "true"} do |g| %>
  <form action="/patients/up_patient" name = "fiche" class="form-horizontal form_patient" id="up_patientss" method="post">
  <div class="modal-body">
    
  <% @patients.each do |pat|%>
  <div class="row-fluid modal_mat">
    <div class="span12"> 
       
    <div class="control-group">
	<% unless pat.archived == true%>
       <input type="checkbox" name = "archive[<%= pat.id%>]" class = "span5" value = "<%= pat.id%>" /> 
       <%else%>
	   <input type="checkbox" name = "archive[<%= pat.id%>]" class = "span5" value = "<%= pat.id%>" checked /> 
      <%end%>
       <label ><%= pat.id%></label> 
      <label ><%= pat.name%></label>     
        <label ><%=pat.first_name%></label> 
        
        </div>   
     
    </div>
    </div>
  
  <%end%>
  <%#= g.hidden_field :table, :id =>'tables'%>
  <input id="tables" name="table" type="hidden" />
 
     
      <input type="submit" value="Archiver" name ="commit" class ="btn btn-primary"/>	
    <%#= g.submit 'Archiver', class: 'btn btn-primary' %>
  
  
        
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <!--<button type="button" class="btn btn-primary">Save</button>-->
                </div>
             </div>
  </form>
            </div>
        </div>
    </div>
</div>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<!--<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Archived</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.archived %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Patient', new_patient_path %>-->

<div style="margin:0 10px 0 10px;">
<h3 style="margin:0;">Liste des patients</h3>
</div>
<!--<div class="row">-->


<div class="span12"> 
<div style="margin:0 10px 10px 10px;">
<%#= render 'shared/title_proc', :title => "", :tabs => 'material' %>
<div class="tab-content">
  <div class="tab-pane active" id="material_data">
<table class="table table-hover">
  <tbody>
 <thead >   
  <tr>
	<th></th>
    <th class="table_th" style="text-align:center;" > Nom </th>  
    <th class="table_th" style="text-align:center;" >Prénom </th>
    <th class="table_th" style="text-align:center;" >Archivé</th>    
  </tr>
 </thead>
 
  <% for mat in @patients.sort_by(&:name).reverse %>
   <tr> 
      <td style="text-align:center;">
      	<%= link_to (fa_icon "times"), delete_patients_path(:p => mat.id), :rel => 'tooltip', :title => 'supprimer', data: { confirm:"Vous voulez vraiment supprimer ce patient?"} %>
      	<%=link_to (fa_icon "edit"),"#myModal_edit_#{mat.id}", :data => {:toggle => "modal"},:rel => 'tooltip',:title => 'Modifier' %>
      	
	  </td>
  
	<%= render 'modal_edit_patient', :ing => mat %>
  
      <td style="text-align:center;"> <%= mat.name %></td>
      <td style="text-align:center;"><%= mat.first_name%></td>
       <%if mat.archived == true %>
            <td style="text-align:center;">Oui</td>        
         <%else%>
           <td style="text-align:center;">Non</td>  
         <%end%>
      
	     
  </tr>
	<% end %>
		<tr>
			<td ><a href="#myModal" role="button" class="btn btn-block btn-info btn-mini" data-toggle="modal"><%= fa_icon "plus" %> ajouter</a>
                      
                         <%= render 'modal_add_patient' %>
                     </td>   
		</tr>
                <% unless @patients.count == 0%>
                <tr>
		<td ><a href="#myModal_up" role="button" class="btn btn-block btn-info btn-mini" data-toggle="modal">Afficher all</a>
                   <%= render 'modal_up_patient' %>
                     </td>   
		</tr>
              <%end%>

  </tbody>  
</table>
 
   </div>
</div>
</div>
</div>
<!--</div>-->

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Archived:</strong>
  <%= @patient.archived %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>